// Authentication types
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const SYNC_REQUEST = 'SYNC_REQUEST';
export const SYNC_SUCCESS = 'SYNC_SUCCESS';
export const SYNC_FAILURE = 'SYNC_FAILURE';
export const FORGOT_REQUEST = 'FORGOT_REQUEST';
export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';
export const FORGOT_FAILURE = 'FORGOT_FAILURE';
export const RESET_REQUEST = 'RESET_REQUEST';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAILURE = 'RESET_FAILURE';
export const LOAD_RESET_REQUEST = 'LOAD_RESET_REQUEST';
export const LOAD_RESET_SUCCESS = 'LOAD_RESET_SUCCESS';
export const LOAD_RESET_FAILURE = 'LOAD_RESET_FAILURE';
export const VERIFY_REQUEST = 'VERIFY_REQUEST';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_FAILURE = 'VERIFY_FAILURE';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Category and habits types
export const ADD_CAT_REQUEST = 'ADD_CAT_REQUEST';
export const ADD_CAT_SUCCESS = 'ADD_CAT_SUCCESS';
export const ADD_CAT_FAILURE = 'ADD_CAT_FAILURE';
export const LOAD_HABITS_REQUEST = 'LOAD_HABITS_REQUEST';
export const LOAD_HABITS_SUCCESS = 'LOAD_HABITS_SUCCESS';
export const LOAD_HABITS_FAILURE = 'LOAD_HABITS_FAILURE';
export const LOAD_HABIT_DATA_REQUEST = 'LOAD_HABIT_DATA_REQUEST';
export const LOAD_HABIT_DATA_SUCCESS = 'LOAD_HABIT_DATA_SUCCESS';
export const LOAD_HABIT_DATA_FAILURE = 'LOAD_HABIT_DATA_FAILURE';
export const ADD_HABIT_REQUEST = 'ADD_HABIT_REQUEST';
export const ADD_HABIT_SUCCESS = 'ADD_HABIT_SUCCESS';
export const ADD_HABIT_FAILURE = 'ADD_HABIT_FAILURE';
export const CHECK_HABIT_REQUEST = 'CHECK_HABIT_REQUEST';
export const CHECK_HABIT_SUCCESS = 'CHECK_HABIT_SUCCESS';
export const CHECK_HABIT_FAILURE = 'CHECK_HABIT_FAILURE';

// Scores types
export const LOAD_SCORES_REQUEST = 'LOAD_SCORES_REQUEST';
export const LOAD_SCORES_SUCCESS = 'LOAD_SCORES_SUCCESS';
export const LOAD_SCORES_FAILURE = 'LOAD_SCORES_FAILURE';

// Friends types
export const LOAD_FRIENDS_REQUEST = 'LOAD_FRIENDS_REQUEST';
export const LOAD_FRIENDS_SUCCESS = 'LOAD_FRIENDS_SUCCESS';
export const LOAD_FRIENDS_FAILURE = 'LOAD_FRIENDS_FAILURE';
export const LOAD_RELATIONSHIPS_REQUEST = 'LOAD_RELATIONSHIPS_REQUEST';
export const LOAD_RELATIONSHIPS_SUCCESS = 'LOAD_RELATIONSHIPS_SUCCESS';
export const LOAD_RELATIONSHIPS_FAILURE = 'LOAD_RELATIONSHIPS_FAILURE';
export const ADD_FRIEND_REQUEST = 'ADD_FRIEND_REQUEST';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
export const ADD_FRIEND_FAILURE = 'ADD_FRIEND_FAILURE';
export const ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST';
export const ACCEPT_FRIEND_SUCCESS = 'ACCEPT_FRIEND_SUCCESS';
export const ACCEPT_FRIEND_FAILURE = 'ACCEPT_FRIEND_FAILURE';
export const REJECT_FRIEND_REQUEST = 'REJECT_FRIEND_REQUEST';
export const REJECT_FRIEND_SUCCESS = 'REJECT_FRIEND_SUCCESS';
export const REJECT_FRIEND_FAILURE = 'REJECT_FRIEND_FAILURE';
export const LOAD_FRIEND_CONTENT_SUCCESS = 'LOAD_FRIEND_CONTENT_SUCCESS';
export const LOAD_FRIEND_CONTENT_FAILURE = 'LOAD_FRIEND_CONTENT_FAILURE';
export const LOAD_FRIEND_CONTENT_REQUEST = 'LOAD_FRIEND_CONTENT_REQUEST';
